---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-creds
  namespace: cloudnative-pg
type: kubernetes.io/basic-auth
stringData:
  username: example
  password: example
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich-creds
  namespace: cloudnative-pg
type: kubernetes.io/basic-auth
stringData:
  username: example
  password: example
