
- hosts: localhost
  become: true
  roles:
    - role: xanmanning.k3s
  tasks:
    - name: Create a file to show Ansible works
      copy:
        dest: /tmp/ansible-pull-success.txt
        content: "Ansible pull ran successfully!"
